export const CREATE_NEW_USER_REQUEST = "CREATE_NEW_USER_REQUEST";
export const CREATE_NEW_USER_SUCCESS = "CREATE_NEW_USER_SUCCESS";
export const CREATE_NEW_USER_FAILD = "CREATE_NEW_USER_FAILD";

export const LOGIN_USER_REQUEST = "LOGIN_USER_REQUEST";
export const LOGIN_USER_SUCCESS = "LOGIN_USER_SUCCESS";
export const LOGIN_USER_FAILD = "LOGIN_USER_FAILD";

export const LOGUOT_USER = "LOGUOT_USER";

export const CHECK_AUTH_REQUEST = "CHECK_AUTH_REQUEST";
export const CHECK_AUTH_SUCCESS = "CHECK_AUTH_SUCCESS";
export const CHECK_AUTH_FAILD = "CHECK_AUTH_FAILD";




//Card Actions
export const CREATE_NEW_CARD_REQUEST = "CREATE_NEW_CARD_REQUEST";
export const CREATE_NEW_CARD_SUCCESS = "CREATE_NEW_CARD_SUCCESS";
export const CREATE_NEW_CARD_FAILD = "CREATE_NEW_CARD_FAILD";
